Capstone project
iLynette/sheCodes-capstone pull request #1
Opened 2022-02-03 12:32 UTC by iLynette

- In this project i implemented the following;
- I built the `about` and `home` page with versions for different screen sizes.
- Linked the `homepage` to the logo
- Linked the `about` page to the home page
- Created the featured speakers section dynamically using` javascript`.

Link to loom video https://www.loom.com/share/5a90b005e02640c48415b6926e2e0bdd

2022-02-03 14:30 UTC, medaminedev66 requested changes
Hi @student, :wave:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Key Highlights

- your code organization was really good.

## Required Changes ♻️

_See the inline comments below for more required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 14:30 UTC, medaminedev66 commented on README.md
> +To get a local copy up and running you just need to have a browser of your choice
- It would be better to add more details on how to use the project locally so the visitors know how to use your project.

2022-02-03 14:30 UTC, medaminedev66 commented on README.md
- [x] Make sure the README contains an "Acknowledgements" section that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the author of the original design, as required by the [Creative Commons License.](https://creativecommons.org/licenses/?lang=en)

2022-02-03 14:30 UTC, medaminedev66 commented on about.html
> +            </ul>
- [x] It would be better to change the font family to `"Lato", sans-serif` for the elements that I took screenshots of (Check them below). Remember to stick to the design that is provided in the template as much as you can (Fonts, Colors ...).

<img width="339" alt="image" src="https://user-images.githubusercontent.com/77190203/152354652-71166d94-8369-4e80-94be-c538384c2b38.png">

<img width="376" alt="image" src="https://user-images.githubusercontent.com/77190203/152354754-b7c3c614-bae0-49af-b99f-97d9c0523c5e.png">

<img width="157" alt="image" src="https://user-images.githubusercontent.com/77190203/152354878-fcba6768-1356-4030-8299-2c2786ef01f3.png">

<img width="203" alt="image" src="https://user-images.githubusercontent.com/77190203/152354974-b9636cbd-fba2-43ba-ba04-6ddecbee6e8b.png">

<img width="596" alt="image" src="https://user-images.githubusercontent.com/77190203/152355067-523c5214-63e9-4bf2-b383-8af5a83456a7.png">

2022-02-03 14:30 UTC, medaminedev66 commented on index.html
> +    </section>
- Great program section display. 👏 Let's make it even greater by following the margins, padding, and background colors of the original design.
- Your design:
<img width="948" alt="image" src="https://user-images.githubusercontent.com/77190203/152356273-ae0b24b8-d4ae-46a8-9ff8-8e52a5576b84.png">
- Original design:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/77190203/152356492-68f7eb38-e726-40b8-8f02-753e6abee4cb.png">

2022-02-03 14:30 UTC, medaminedev66 commented on index.html
> +    </footer>
- [x] You implemented the footer and the partners' section in a good way 👏. Let's make it even greater by following the margins, padding, fonts, and background colors of the original design.
- [ ] Kindly add the logo of your website to the footer and align it to the left.
- Your design:
<img width="935" alt="image" src="https://user-images.githubusercontent.com/77190203/152357466-bab7867e-d8a8-4b56-a89b-719f6842a721.png">

- Original design:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/77190203/152357606-66568911-a014-4729-b142-7600af5382a2.png">

2022-02-03 14:30 UTC, medaminedev66 commented on index.html
> +            </div>
- [ ] I would recommend changing the logo to improve your design and make it professional. the background color of the logo is white color which doesn't fit the background color of the header.
- Your logo:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/77190203/152358408-cd68ae01-7f90-45cf-8882-af40fc6a5b4f.png">

2022-02-03 14:30 UTC, medaminedev66 commented on index.html
> +    </section>
- [ ] There is an overlap between the `learning` section and `Program` section. I would highly recommend fixing it to improve the UI design.
- Your design:
<img width="209" alt="image" src="https://user-images.githubusercontent.com/77190203/152359758-852583ae-d950-4846-8cf6-ded297e29099.png">

2022-02-03 14:30 UTC, medaminedev66 commented on script.js
> +});
- [ ] The Menu doesn't show up when the user clicks on the hamburger icon for the first time. but it works for the second time. Let's try to fix it.

2022-02-03 19:57 UTC, Deepakdanger requested changes
Hi @iLynette, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-02-03 19:57 UTC, Deepakdanger commented on about.html
> +    <footer class="icons2">
- [ ] **Required** In the Mobile version, the `footer section` the background is white along with your logo on the left side.
- Your design
![qdq](https://user-images.githubusercontent.com/26767383/152418171-1427931e-1da7-4232-9e6d-a837641b6e1a.PNG)
- Original design
![ggg](https://user-images.githubusercontent.com/26767383/152418232-f45f837f-efb9-4201-8471-226ecc874739.PNG)

2022-02-03 19:57 UTC, Deepakdanger commented on about.html
> +    </footer>
- [ ] **Required** In mobile version ,The `about page ` `footer section` is same as `home` page footer. Right now there is text with the color white present there, Kindly fix that.

2022-02-04 05:14 UTC, ShoiraTa approved these changes
### **STATUS: APPROVED  ✔️** 
------
Hi @iLynette ,  

Your project is complete! Great job for nailing it. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-04 05:19 UTC, merged